import type React from "react";

export default function DataScienceIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="800px"
      height="800px"
      viewBox="0 0 48 48"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect
        x="1"
        y="1"
        width="46"
        height="46"
        rx="4"
        ry="4"
        transform="translate(48 48) rotate(180)"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinejoin="round"
      />
      <rect
        x="4"
        y="22"
        width="7"
        height="22"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <rect
        x="15"
        y="28"
        width="7"
        height="16"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <rect
        x="26"
        y="19"
        width="7"
        height="25"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <rect
        x="37"
        y="23"
        width="7"
        height="21"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="7"
        cy="14"
        r="2"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="19"
        cy="20"
        r="2"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="30"
        cy="11"
        r="2"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="41"
        cy="15"
        r="2"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <line
        x1="9"
        y1="15"
        x2="17"
        y2="19"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <line
        x1="21"
        y1="19"
        x2="28"
        y2="12"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <line
        x1="32"
        y1="12"
        x2="39"
        y2="14"
        fill="none"
        stroke="#1d1d1b"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
